import { NextRequest, NextResponse } from "next/server";
import Stripe from "stripe";

export async function POST(req: NextRequest) {
  const body = await req.text();
  const sig = req.headers.get("stripe-signature") || "";

  let event: Stripe.Event;

  try {
    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY || "");
    event = stripe.webhooks.constructEvent(body, sig, process.env.STRIPE_WEBHOOK_SECRET || "");
  } catch (err: any) {
    console.error("Webhook sig failed:", err.message);
    return NextResponse.json({ error: "Invalid signature" }, { status: 400 });
  }

  if (event.type === "checkout.session.completed") {
    const session = event.data.object as Stripe.Checkout.Session;
    const { name, birth, time, gender, city, product, refCode } = session.metadata || {};
    const email = session.customer_details?.email || "";
    const amount = (session.amount_total || 0) / 100;

    console.log("Payment OK:", { name, email, product, amount, refCode });

    try {
      const { default: prisma } = await import("@/lib/prisma");

      // Commission
      let commissionAmount = 0;
      let referrerId: string | null = null;

      if (refCode) {
        const partner = await prisma.partner.findUnique({ where: { refCode } });
        if (partner) {
          referrerId = partner.userId;
          let rate = 0.3;
          if (partner.tier === "silver") rate = 0.4;
          if (partner.tier === "gold") rate = 0.5;
          commissionAmount = Math.round(amount * rate * 100) / 100;

          await prisma.commission.create({
            data: { partnerId: partner.id, orderId: session.id, amount: commissionAmount, status: "pending" },
          });

          // SQLite doesn't support increment, so fetch+update
          const p = await prisma.partner.findUnique({ where: { id: partner.id } });
          if (p) {
            await prisma.partner.update({
              where: { id: partner.id },
              data: {
                totalSales: (p.totalSales || 0) + amount,
                commission: (p.commission || 0) + commissionAmount,
                balance: (p.balance || 0) + commissionAmount,
              },
            });
          }
        }
      }

      let userId: string | null = null;
      if (email) {
        const user = await prisma.user.findUnique({ where: { email } });
        userId = user?.id || null;
      }

      await prisma.order.create({
        data: {
          userId, email,
          product: product || "reading",
          amount, currency: session.currency || "usd",
          status: "paid", sessionId: session.id,
          referrerId,
          commission: commissionAmount > 0 ? commissionAmount : null,
        },
      });

      console.log(`Order saved: ${product} $${amount}${commissionAmount > 0 ? ` commission $${commissionAmount}` : ""}`);
    } catch (e) {
      console.error("DB write failed:", e);
    }

    // Email notification
    try {
      if (process.env.RESEND_API_KEY && email) {
        const { Resend } = await import("resend");
        const resend = new Resend(process.env.RESEND_API_KEY);
        await resend.emails.send({
          from: process.env.EMAIL_FROM || "noreply@bking.one",
          to: email,
          subject: `🔮 Your Fortune Report | ${name || "Dear User"}`,
          html: `<div style="max-width:600px;margin:auto;font-family:sans-serif;color:#e5e5e5;background:#0a0a0f;padding:40px;border-radius:12px"><h1 style="color:#f59e0b;">🔮 MingShi BKing</h1><p>Thank you, <strong style="color:#f59e0b;">${name || "Dear User"}</strong>!</p><p>Your ${product === "naming" ? "naming" : "chart reading"} report is being generated by AI. You will receive it within 10 minutes.</p><hr style="border-color:#333;margin:24px 0"><p style="font-size:14px;color:#666">MingShi BKing · AI Fortune Lab</p></div>`,
        });
      }
    } catch (e) {
      console.error("Email failed:", e);
    }
  }

  return NextResponse.json({ received: true });
}
